baseURL = 'https://semolex.online/'
languageCode = 'en-us'
title = 'semolex.online'
enableEmoji = true
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "HugoTeX"

[pagination]
  pagerSize = 5

[Params.Author]
  name = "Oleksii Semeshchuk"
  abstract = """
  I'm a software engineer, musician and amateur astronomer.
  All thought are opinionated.
  """

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[params]
    description = "Personal blog of Oleksii Semeshchuk"
    keywords = "programming, music, astronomy, software engineering"
    author = "Oleksii Semeshchuk"
    email = "semolex@live.com"
    github = "https://github.com/semolex"
    linkedin = "https://www.linkedin.com/in/oleksiy-semeshchuk-4536a632/"
    twitter = "https://twitter.com/semolex"
